### ISSUE TITLE
Client receiving python error OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by tardis79** [earthquake/XFLTReaT#7] opened 2019-11-22 17:18 UTC
Whenever I run XFLTReaT.py on ubuntu client, I get this error.
I don't know much about python so if you could help I would really appreciate it:)

root@ubuntu:/home/ubuntu/XFLTReaT# python xfltreat.py --client
,--.   ,--.,------.,--.,--------.,------.                ,--------. 
 \  `.'  / |  .---'|  |'--.  .--'|  .--. ' ,---.  ,--,--.'--.  .--' 
  .'    \  |  `--, |  |   |  |   |  '--'.'| .-. :' ,-.  |   |  |    
 /  .'.  \ |  |`   |  '--.|  |   |  |\  \ \   --.\ '-'  |   |  |    
'--'   '--'`--'    `-----'`--'   `--' '--' `----' `--`--'   `--'    
Balazs Bucsay [[@xoreipeip]]

[*] Parsing config file
[-] The 'key' option's value in the Authentication section is a bit short, it is recommended to make it longer
[*] Loading all modules from 'modules' directory
[*] Setting up interface
Traceback (most recent call last):
  File "xfltreat.py", line 395, in <module>
    xfltreat.run(sys.argv[1:])
  File "xfltreat.py", line 272, in run
    config.get("Global", "clientip"), config.get("Global", "serverip"), config.get("Global", "clientnetmask"))
  File "/home/ubuntu/XFLTReaT/interface.py", line 186, in lin_set_ip_address
    ps = subprocess.Popen(["route", "add", "-net", rangeip, "netmask", netmask, "dev", dev], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by earthquake** [comment] 2019-12-03 17:49
Sorry I was away. It is pretty strange. Are you running it as root? Do you have the "route" command? They might have removed it from the OS in this release. Can you check it please and get back to me? Thanks.

**Comment by earthquake** [comment] 2019-12-08 21:38
The bug report process should involve multiple steps, not just reporting a bug that happened on one system. Without the details I cannot reproduce it and make decisions whether it was user error, distribution related issue or something else.
I am going to close this because of the lack of answer. Feel free to reopen it in case it still persists and ready to give more information.

**Closed as completed** 2019-12-08 21:38 UTC
